#pragma checksum "C:\Users\Dandy\source\repos\SmartEduERP\SmartEduERP - Copy 2\SmartEduERP\Platforms\Windows\App.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "BC644117F53186F75D5C3C68621A56F22B8A877D2D81E69D0263C85E5E28B52B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartEduERP.WinUI
{
    partial class App : global::Microsoft.Maui.MauiWinUIApplication
    {
    }
}

